services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: antares
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    ports:
      - "5432:5432"
    secrets:
      - db_password

  pgadmin4:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: test@antares.com
      PGADMIN_DEFAULT_PASSWORD_FILE: /run/secrets/pgadmin_password
    ports:
      - "8080:80"
    depends_on:
      - db
    secrets:
      - pgadmin_password

secrets:
  db_password:
    file: credentials/db_password.txt
  pgadmin_password:
    file: credentials/pgadmin_password.txt